# Generated by Django 2.1.7 on 2019-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20190212_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.BooleanField(),
        ),
    ]
